import { BusinessType } from "./types";

export interface Theme {
  label: string;
  bg: string;
  surface: string;
  surfaceAlt: string;
  text: string;
  textMuted: string;
  accent: string;
  accentHover: string;
  accentText: string;
  border: string;
  heroBg: string;
  heroPattern: string;
  fontDisplay: string;
  fontBody: string;
  navStyle: string;
  heroOverlay: string;
  sectionPad: string;
  vibe: string;
}

export const themes: Record<BusinessType, Theme> = {
  restaurant: {
    label: "Warm & Inviting",
    bg: "bg-[#FBF7F1]",
    surface: "bg-white",
    surfaceAlt: "bg-[#F3EADB]",
    text: "text-[#2C1810]",
    textMuted: "text-[#6B5647]",
    accent: "bg-[#A0522D]",
    accentHover: "hover:bg-[#8B4513]",
    accentText: "text-[#A0522D]",
    border: "border-[#E8DCC8]",
    heroBg: "bg-gradient-to-br from-[#FBF7F1] via-[#F8EFE0] to-[#F3E4CA]",
    heroPattern: "",
    fontDisplay: "font-serif",
    fontBody: "font-sans",
    navStyle: "bg-white/80 backdrop-blur-md",
    heroOverlay: "bg-[#2C1810]/5",
    sectionPad: "py-24",
    vibe: "warm",
  },
  cafe: {
    label: "Cozy & Artisan",
    bg: "bg-[#F7F3ED]",
    surface: "bg-white",
    surfaceAlt: "bg-[#EEE5D5]",
    text: "text-[#3B2817]",
    textMuted: "text-[#7A6B5A]",
    accent: "bg-[#6F4E37]",
    accentHover: "hover:bg-[#5A3F2C]",
    accentText: "text-[#6F4E37]",
    border: "border-[#E0D4BF]",
    heroBg: "bg-gradient-to-br from-[#F7F3ED] to-[#E8DDC8]",
    heroPattern: "",
    fontDisplay: "font-serif",
    fontBody: "font-sans",
    navStyle: "bg-white/80 backdrop-blur-md",
    heroOverlay: "bg-[#3B2817]/5",
    sectionPad: "py-24",
    vibe: "warm",
  },
  gym: {
    label: "Bold & Powerful",
    bg: "bg-[#0A0A0A]",
    surface: "bg-[#141414]",
    surfaceAlt: "bg-[#1A1A1A]",
    text: "text-white",
    textMuted: "text-white/60",
    accent: "bg-[#FF3B30]",
    accentHover: "hover:bg-[#E5342A]",
    accentText: "text-[#FF3B30]",
    border: "border-white/10",
    heroBg: "bg-gradient-to-br from-black via-[#0F0F0F] to-[#1A0505]",
    heroPattern: "",
    fontDisplay: "font-display",
    fontBody: "font-sans",
    navStyle: "bg-black/80 backdrop-blur-md",
    heroOverlay: "bg-black/20",
    sectionPad: "py-28",
    vibe: "bold",
  },
  salon: {
    label: "Elegant & Refined",
    bg: "bg-[#FDFBF9]",
    surface: "bg-white",
    surfaceAlt: "bg-[#F5ECE4]",
    text: "text-[#2B1D1D]",
    textMuted: "text-[#7A6B6B]",
    accent: "bg-[#B76E79]",
    accentHover: "hover:bg-[#A05D69]",
    accentText: "text-[#B76E79]",
    border: "border-[#EADFD5]",
    heroBg: "bg-gradient-to-br from-[#FDFBF9] via-[#F7EDE6] to-[#EDDDD1]",
    heroPattern: "",
    fontDisplay: "font-serif",
    fontBody: "font-sans",
    navStyle: "bg-white/80 backdrop-blur-md",
    heroOverlay: "bg-[#2B1D1D]/5",
    sectionPad: "py-24",
    vibe: "elegant",
  },
  clinic: {
    label: "Clean & Trusted",
    bg: "bg-[#F8FBFE]",
    surface: "bg-white",
    surfaceAlt: "bg-[#EDF4FB]",
    text: "text-[#0F2847]",
    textMuted: "text-[#5A6B80]",
    accent: "bg-[#2563EB]",
    accentHover: "hover:bg-[#1E4FCB]",
    accentText: "text-[#2563EB]",
    border: "border-[#DCE6F3]",
    heroBg: "bg-gradient-to-br from-[#F8FBFE] via-[#EEF4FC] to-[#DEE9F8]",
    heroPattern: "",
    fontDisplay: "font-sans",
    fontBody: "font-sans",
    navStyle: "bg-white/80 backdrop-blur-md",
    heroOverlay: "bg-[#0F2847]/5",
    sectionPad: "py-24",
    vibe: "clean",
  },
  studio: {
    label: "Creative & Sleek",
    bg: "bg-[#FAFAFA]",
    surface: "bg-white",
    surfaceAlt: "bg-[#F0F0F0]",
    text: "text-[#0A0A0A]",
    textMuted: "text-[#6B6B6B]",
    accent: "bg-[#0A0A0A]",
    accentHover: "hover:bg-[#2B2B2B]",
    accentText: "text-[#0A0A0A]",
    border: "border-[#E8E8E8]",
    heroBg: "bg-gradient-to-br from-white via-[#FAFAFA] to-[#F0F0F0]",
    heroPattern: "",
    fontDisplay: "font-display",
    fontBody: "font-sans",
    navStyle: "bg-white/80 backdrop-blur-md",
    heroOverlay: "bg-black/5",
    sectionPad: "py-24",
    vibe: "modern",
  },
  shop: {
    label: "Fresh & Playful",
    bg: "bg-[#FAFAF5]",
    surface: "bg-white",
    surfaceAlt: "bg-[#F0F4E8]",
    text: "text-[#1A2E1F]",
    textMuted: "text-[#5A6B5A]",
    accent: "bg-[#2D6A4F]",
    accentHover: "hover:bg-[#24553F]",
    accentText: "text-[#2D6A4F]",
    border: "border-[#DDE5D3]",
    heroBg: "bg-gradient-to-br from-[#FAFAF5] via-[#F0F4E8] to-[#E3ECD5]",
    heroPattern: "",
    fontDisplay: "font-display",
    fontBody: "font-sans",
    navStyle: "bg-white/80 backdrop-blur-md",
    heroOverlay: "bg-[#1A2E1F]/5",
    sectionPad: "py-24",
    vibe: "fresh",
  },
  agency: {
    label: "Sharp & Modern",
    bg: "bg-[#0B0F17]",
    surface: "bg-[#141927]",
    surfaceAlt: "bg-[#1A2033]",
    text: "text-white",
    textMuted: "text-white/60",
    accent: "bg-[#6366F1]",
    accentHover: "hover:bg-[#5557E8]",
    accentText: "text-[#818CF8]",
    border: "border-white/10",
    heroBg: "bg-gradient-to-br from-[#0B0F17] via-[#141B30] to-[#1E1B4B]",
    heroPattern: "",
    fontDisplay: "font-display",
    fontBody: "font-sans",
    navStyle: "bg-[#0B0F17]/80 backdrop-blur-md",
    heroOverlay: "bg-black/20",
    sectionPad: "py-28",
    vibe: "sharp",
  },
};

export const BUSINESS_TYPE_OPTIONS: { value: BusinessType; label: string; emoji: string }[] = [
  { value: "restaurant", label: "Restaurant", emoji: "🍽️" },
  { value: "cafe", label: "Café", emoji: "☕" },
  { value: "gym", label: "Gym / Fitness", emoji: "💪" },
  { value: "salon", label: "Salon / Spa", emoji: "💄" },
  { value: "clinic", label: "Clinic / Dental", emoji: "🏥" },
  { value: "studio", label: "Studio / Photo", emoji: "📸" },
  { value: "shop", label: "Shop / Retail", emoji: "🛍️" },
  { value: "agency", label: "Agency / Tech", emoji: "💼" },
];
